# Generated by Django 3.2.11 on 2022-02-14 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cartapp', '0003_alter_cart_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cart',
            unique_together=set(),
        ),
    ]
