# Generated by Django 3.2.11 on 2022-02-26 21:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_auto_20220224_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='age',
            field=models.PositiveIntegerField(default=18, verbose_name='возраст'),
        ),
        migrations.AlterField(
            model_name='shopuser',
            name='city',
            field=models.CharField(blank=True, max_length=20, verbose_name='город'),
        ),
        migrations.AlterField(
            model_name='shopuser',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='телефон'),
        ),
        migrations.CreateModel(
            name='ShopUserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.TextField(blank=True, max_length=512, verbose_name='о себе')),
                ('gender', models.CharField(choices=[('M', 'Мужской'), ('F', 'Женский'), ('X', 'Небинарный')], max_length=1, verbose_name='гендер')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
