# Generated by Django 3.2.11 on 2022-04-02 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordersapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('CREATED', 'создан'), ('IN_PROCESSING', 'в обработке'), ('AWAITING_PAYMENT', 'ожидает оплаты'), ('PAID', 'оплачен'), ('READY', 'готов'), ('CANCELED', 'отменён'), ('FINISHED', 'выполнен')], default='CREATED', max_length=30, verbose_name='статус'),
        ),
    ]
